# -*- coding: utf-8 -*-
"""Worksheet0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FyHVWRjnXd3Wx1Ml__XnTYRHP88tmOh
"""

import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

name = "Alice"
greeting = "Hello"
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

"""To-Do-Task

**Task1**
"""

def convert_units(value, conversion_type):

    if conversion_type == 1:  # meters to feet
        return value * 3.28084
    elif conversion_type == 2:  # feet to meters
        return value / 3.28084
    elif conversion_type == 3:  # kg to pounds
        return value * 2.20462
    elif conversion_type == 4:  # pounds to kg
        return value / 2.20462
    elif conversion_type == 5:  # liters to gallons
        return value * 0.264172
    elif conversion_type == 6:  # gallons to liters
        return value / 0.264172
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("\nChoose Conversion Type:")
    print("1. Length: meters to feet")
    print("2. Length: feet to meters")
    print("3. Weight: kilograms to pounds")
    print("4. Weight: pounds to kilograms")
    print("5. Volume: liters to gallons")
    print("6. Volume: gallons to liters")

    try:
        choice = int(input("\nEnter your choice (1-6): "))
        value = float(input("Enter the value to convert: "))

        result = convert_units(value, choice)

        if result is None:
            print("Unsupported conversion type.")
        else:
            print("Converted value:", result)

    except ValueError:
        print("Invalid input! Please enter numeric values only.")


if __name__ == "__main__":
    main()

"""**Task2**"""

def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of all numbers in the list.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average value of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Finds the maximum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The largest number in the list.
    """
    return max(numbers)


def find_min(numbers):
    """
    Finds the minimum number in a list.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The smallest number in the list.
    """
    return min(numbers)


def main():
    print("Mathematical Operations on a List")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    try:
        choice = int(input("Choose an operation (1-4): "))

        user_input = input("Enter numbers separated by spaces: ")
        numbers = [float(num) for num in user_input.split()]

        if len(numbers) == 0:
            raise ValueError("The list is empty.")

        if choice == 1:
            result = find_sum(numbers)
            print("Sum:", result)

        elif choice == 2:
            result = find_average(numbers)
            print("Average:", result)

        elif choice == 3:
            result = find_max(numbers)
            print("Maximum:", result)

        elif choice == 4:
            result = find_min(numbers)
            print("Minimum:", result)

        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Invalid input! Please enter valid numbers.")


if __name__ == "__main__":
    main()

"""List Manipulation:"""

def extract_every_other(lst):
    """
    Returns every other element from the given list, starting from the first element.

    Parameters:
    lst (list): The input list of elements.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]

numbers = [1, 2, 3, 4, 5, 6, 7]
result = extract_every_other(numbers)
print("Output:", result)

"""Slice a Sublist:"""

def get_sublist(lst, start, end):

    return lst[start:end+1]

numbers = [1, 2, 3, 4, 5, 6]


result = get_sublist(numbers,2,4)
print("Output:", result)

"""Reverse a List Using Slicing:"""

def reverse_list(lst):
    return lst[::-1]

numbers = [1, 2, 3, 4, 5, 6, 7]
result = reverse_list(numbers)
print("Output:", result)

"""Remove first and last element"""

def remove_first_last(lst):
    return lst[1:-1]

numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print("Output:", result)

"""Get the First n Elements:"""

def get_first_n(lst, n):
    return lst[:n]

numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)
print("Output:", result)

"""Extract Elements from the End:"""

def get_last_n(lst, n):
    return lst[-n:]

numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print("Output:", result)

"""Extract Elements in Reverse Order:"""

def reverse_skip(lst):
    return lst[::-2]

numbers = [1, 2, 3, 4, 5]
result = reverse_skip(numbers)
print("Output:", result)

"""Nested list"""

def flatten(lst):

    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(item)  # add elements of sublist
        else:
            flat_list.append(item)  # add single element
    return flat_list

nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)
print("Flattened List:", result)

"""Accessing Nested List Elements:"""

def access_nested_element(lst, indices):
    element = lst
    for idx in indices:
        element = element[idx]  # go deeper into the nested list
    return element

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print("Output:", result)

"""Sum of All Elements in a Nested List:"""

def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, including sublists at any depth.

    Parameters:
    lst (list): A nested list of numbers.

    Returns:
    int/float: Sum of all numbers in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # recursive call for sublist
        else:
            total += item  # add number directly
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print("Sum of all elements:", result)

"""Remove Specific Element from a Nested List:"""

def remove_element(lst, elem):
    """
    Removes all occurrences of elem from a nested list.

    Parameters:
    lst (list): A nested list of elements.
    elem: The element to remove from the list.

    Returns:
    list: A new nested list with all occurrences of elem removed.
    """
    new_list = []
    for item in lst:
        if isinstance(item, list):
            # Recursively remove element from sublist
            new_list.append(remove_element(item, elem))
        else:
            if item != elem:
                new_list.append(item)
    return new_list

nested_list = [[1, 2], [3, 2], [4, 5]]
result = remove_element(nested_list, 2)
print("Modified List:", result)

"""Find the Maximum Element in a Nested List:"""

def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list of numbers.

    Returns:
    int/float: The maximum number in the nested list.
    """
    max_value = float('-inf')  # start with smallest possible number
    for item in lst:
        if isinstance(item, list):
            # recursive call for sublist
            sub_max = find_max(item)
            if sub_max > max_value:
                max_value = sub_max
        else:
            if item > max_value:
                max_value = item
    return max_value

nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print("Maximum Element:", result)

"""Count Occurrences of an Element in a Nested List:"""

def count_occurrences(lst, elem):
    """
    Counts how many times elem appears in a nested list.

    Parameters:
    lst (list): A nested list of elements.
    elem: The element to count.

    Returns:
    int: Number of times elem appears in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            # Recursive call for sublist
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
result = count_occurrences(nested_list, 2)
print("Occurrences of 2:", result)

"""Flatten a List of Lists of Lists:"""

def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
    lst (list): A nested list of arbitrary depth.

    Returns:
    list: A new flattened list containing all elements.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            # Recursively flatten the sublist
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print("Flattened List:", result)

"""Nested List Average:"""

def average_nested(lst):
    """
    Calculates the average of all numbers in a nested list.

    Parameters:
    lst (list): A nested list of numbers.

    Returns:
    float: Average of all numbers in the nested list.
    """
    def flatten_and_count(lst):
        """
        Helper function that returns a tuple (total_sum, total_count)
        of all numbers in the nested list.
        """
        total_sum = 0
        total_count = 0
        for item in lst:
            if isinstance(item, list):
                sub_sum, sub_count = flatten_and_count(item)
                total_sum += sub_sum
                total_count += sub_count
            else:
                total_sum += item
                total_count += 1
        return total_sum, total_count

    total, count = flatten_and_count(lst)
    if count == 0:
        return 0  # avoid division by zero
    return total / count

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print("Average:", result)

"""# To - Do - NumPy

Basic Vector and Matrix Operation with Numpy.
"""

import numpy as np

"""1. Initialize an empty array with size 2 × 2"""

arr1= np.empty((2,2))
print(arr1)

"""Initialize an all one array with size 4X2."""

arr1= np.ones((4,2))
print(arr1)

"""3. Create a new array of a given shape filled with a value"""

arr1= np.full((4,2),4)
print(arr1)

"""4. Create an array of zeros with the same shape and type as another array"""

arr1= np.zeros_like((2,2))
print(arr1)

"""6. Convert a list into a NumPy array"""

my_list = [1,2,3,4]
arr1= np.array(my_list)
print(arr1)

"""**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

1. Create an array with values ranging from 10 to 49.
"""

import numpy as np

arr1 = np.arange(10, 50)
print(arr1)

"""2. Create a 3 × 3 matrix with values from 0 to 8"""

arr1 = np.arange(9).reshape(3,3)
print(arr1)

"""3. Create a 3 × 3 identity matrix"""

arr1 = np.eye(3)
print(arr1)

"""4. Create a random array of size 30 and find the mean"""

arr1 =np.random.random(30)
print(arr1.mean())

"""5. Create a 10 × 10 random array and find minimum and maximum"""

arr1 =np.random.random((10,10))
print(arr1.min())
print(arr1.max())

"""6. Create a zero array of size 10 and replace 5th element with 1"""

arr1= np.zeros(10)
arr1[4]=1
print(arr1)

"""7. Reverse the array"""

arr = np.array([1,2,0,0,4,0])
rev = arr[::-1]
print(rev)

"""8. Create a 2D array with 1 on border and 0 inside"""

arr1 = np.ones((5,5))
arr1[1:-1,1:-1] = 0
print(arr1)

"""9. Create an 8 × 8 checkerboard matrix"""

arr1 = np.zeros((8,8))
arr1[1::2, ::2] = 1
arr1[::2, 1::2] = 1
print(arr1)

"""# Problem - 3: Array Operations:"""

import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

"""1. Add the two arrays"""

add = x +y
print(add)

"""2. Subtract the two arrays"""

sub = x - y
print(sub)

"""3. Multiply the array with any integer"""

mul = x * 2
print(mul)

"""4. Square each element of the array"""

square = y ** 2
print(square)

"""5. Dot product"""

dot_vw = np.dot(v,w)
print(dot_vw)

dot_xv = np.dot(x, v)
print(dot_xv)

dot_xy = np.dot(x, y)
print(dot_xy)

"""6. Concatenate arrays"""

row_concat = np.concatenate((x, y), axis=0)
print(row_concat)

col_concat = np.vstack((v, w))
print(col_concat)

"""7. Concatenate x and v"""

np.concatenate((x, v))

"""An error occurs because:

x is a 2D array (2 × 2 matrix)

v is a 1D array (vector)

For concatenation, arrays must have the same number of dimensions. Since the dimensions are different, NumPy raises an error.
"""

v2 = v.reshape(1,2)
np.concatenate((x, v2), axis=0)

"""#Problem - 4: Matrix Operations:"""

import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

"""1. Prove A. A-1 = I"""

A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)

print(result)

"""2. Prove
𝐴
𝐵
≠
𝐵
𝐴

"""

AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB =\n", AB)
print("BA =\n", BA)

"""3. Prove (AB)^T = B^TA^T"""

AB = np.dot(A,B)

left = AB.T
right = np.dot(B.T, A.T)

print("(AB)^T =\n", left)
print("B^T A^T =\n", right)

"""Solve the system of linear equations

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9
"""

AX=B
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution:", X)

X = np.linalg.solve(A, B)
print(X)

"""1. Element-wise Addition"""

import numpy as np
import time

#python list
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result = [list1[i] + list2[i] for i in range(size)]

end = time.time()

print("Python List Addition Time:", end - start)

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()

result = arr1 + arr2

end = time.time()

print("NumPy Addition Time:", end - start)

"""2. Element-wise Multiplication"""

start = time.time()

result = [list1[i] * list2[i] for i in range(size)]

end = time.time()

print("Python List Multiplication Time:", end - start)

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()

result = arr1 * arr2

end = time.time()

print("NumPy Multiplication Time:", end - start)

"""3. Dot Product"""

start = time.time()

dot = sum(list1[i] * list2[i] for i in range(size))

end = time.time()

print("Python List Dot Product Time:", end - start)

start = time.time()

dot = np.dot(arr1, arr2)

end = time.time()

print("NumPy Dot Product Time:", end - start)

"""4. Matrix Multiplication"""

size = 1000

A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start = time.time()

result = [[sum(A[i][k] * B[k][j] for k in range(size))
          for j in range(size)]
          for i in range(size)]

end = time.time()

print("Python Matrix Multiplication Time:", end - start)

A = np.ones((1000,1000))
B = np.ones((1000,1000))

start = time.time()

result = np.dot(A,B)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)